### custom parameters #####

INPUT_DIR: '/zp1/data/mhu10/ProjectOMB2/SnakemakeWorkflow/SMK_DataSets/ChIPseq/'
WORK_DIR: '/zp1/data/mhu10/ProjectOMB2/SnakemakeWorkflow/SMK_ChIPseq/'

BOWTIE2INDEX: '/zp1/data/mhu10/ProjectOMB2/SnakemakeWorkflow/SMK_Genomes/Bowtie2Index_premake/GRCm38_NCBI/GRCm38 '

HOMER_MERGE_CTL: ['IIR1','IIR2','IIR3']

HOMER_MERGE_TREATMENT: ['IRF1','IRF2','IRF3']

NAME_CTL: 'IIR'

NAME_TREATMENT: 'IRF'